import { ListIndex } from './src/main/ets/pages/list/ListIndex';
import { GridIndex } from './src/main/ets/pages/grid/GridIndex';
import { FlowIndex } from './src/main/ets/pages/flow/FlowIndex';
import { Rv1WebViewPage } from './src/main/ets/pages/rv/v1/Rv1WebViewPage';
import { Rv1WaterFlowUpAndDownPage } from './src/main/ets/pages/rv/v1/Rv1WaterFlowUpAndDownPage';
import { Rv1RefreshUpAndDownPage } from './src/main/ets/pages/rv/v1/Rv1RefreshUpAndDownPage';
import { Rv1RefreshScrollPage } from './src/main/ets/pages/rv/v1/Rv1RefreshScrollPage';
import { Rv1RefreshPointPage } from './src/main/ets/pages/rv/v1/Rv1RefreshPointPage';
import { Rv1RefreshImmersivePage } from './src/main/ets/pages/rv/v1/Rv1RefreshImmersivePage';
import { Rv1RefreshHeaderAndFooterPage } from './src/main/ets/pages/rv/v1/Rv1RefreshHeaderAndFooterPage';
import { Rv1NoScrollSpringPage } from './src/main/ets/pages/rv/v1/Rv1NoScrollSpringPage';
import { Rv1MultiViewPage } from './src/main/ets/pages/rv/v1/Rv1MultiViewPage';
import { Rv1MaxScrollSpringPage } from './src/main/ets/pages/rv/v1/Rv1MaxScrollSpringPage';
import { Rv1LoadDataSpringBackPage } from './src/main/ets/pages/rv/v1/Rv1LoadDataSpringBackPage';
import { Rv1ListUpAndDownPage } from './src/main/ets/pages/rv/v1/Rv1ListUpAndDownPage';
import { Rv1LazyDataOperationPage } from './src/main/ets/pages/rv/v1/Rv1LazyDataOperationPage';
import { Rv1Index } from './src/main/ets/pages/rv/v1/Rv1Index';
import { Rv1GridUpAndDownPage } from './src/main/ets/pages/rv/v1/Rv1GridUpAndDownPage';
import { Rv1FooterNothingPage } from './src/main/ets/pages/rv/v1/Rv1FooterNothingPage';
import { Rv1FixedFooterPage } from './src/main/ets/pages/rv/v1/Rv1FixedFooterPage';
import { Rv1AutoRefreshPage } from './src/main/ets/pages/rv/v1/Rv1AutoRefreshPage';
import { Rv1AutoListUpAndDownPage } from './src/main/ets/pages/rv/v1/Rv1AutoListUpAndDownPage';
import { Rv1AdaptiveHeightPage } from './src/main/ets/pages/rv/v1/Rv1AdaptiveHeightPage';
import { LitheV1WebViewPage } from './src/main/ets/pages/lithe/v1/LitheV1WebViewPage';
import { LitheV1WaterFlowUpAndDownPage } from './src/main/ets/pages/lithe/v1/LitheV1WaterFlowUpAndDownPage';
import { LitheV1RefreshUpAndDownPage } from './src/main/ets/pages/lithe/v1/LitheV1RefreshUpAndDownPage';
import { LitheV1RefreshScrollPage } from './src/main/ets/pages/lithe/v1/LitheV1RefreshScrollPage';
import { LitheV1RefreshPointPage } from './src/main/ets/pages/lithe/v1/LitheV1RefreshPointPage';
import { LitheV1RefreshImmersivePage } from './src/main/ets/pages/lithe/v1/LitheV1RefreshImmersivePage';
import { LitheV1RefreshHeaderAndFooterPage } from './src/main/ets/pages/lithe/v1/LitheV1RefreshHeaderAndFooterPage';
import { LitheV1NoScrollSpringPage } from './src/main/ets/pages/lithe/v1/LitheV1NoScrollSpringPage';
import { LitheV1MultiViewPage } from './src/main/ets/pages/lithe/v1/LitheV1MultiViewPage';
import { LitheV1LoadDataSpringBackPage } from './src/main/ets/pages/lithe/v1/LitheV1LoadDataSpringBackPage';
import { LitheV1ListUpAndDownPage } from './src/main/ets/pages/lithe/v1/LitheV1ListUpAndDownPage';
import { LitheV1ListMaxSpringPage } from './src/main/ets/pages/lithe/v1/LitheV1ListMaxSpringPage';
import { LitheV1LazyDataOperationPage } from './src/main/ets/pages/lithe/v1/LitheV1LazyDataOperationPage';
import { LitheV1LayoutHeaderPage } from './src/main/ets/pages/lithe/v1/LitheV1LayoutHeaderPage';
import { LitheV1Index } from './src/main/ets/pages/lithe/v1/LitheV1Index';
import { LitheV1GridUpAndDownPage } from './src/main/ets/pages/lithe/v1/LitheV1GridUpAndDownPage';
import { LitheV1FooterNothingPage } from './src/main/ets/pages/lithe/v1/LitheV1FooterNothingPage';
import { LitheV1FixedFooterPage } from './src/main/ets/pages/lithe/v1/LitheV1FixedFooterPage';
import { LitheV1AutoRefreshPage } from './src/main/ets/pages/lithe/v1/LitheV1AutoRefreshPage';
import { LitheV1AutoListUpAndDownPage } from './src/main/ets/pages/lithe/v1/LitheV1AutoListUpAndDownPage';
import { LitheV1AdaptiveHeightPage } from './src/main/ets/pages/lithe/v1/LitheV1AdaptiveHeightPage';
import { ListViewUpAndDownPage } from './src/main/ets/pages/list/v1/view/ListViewUpAndDownPage';
import { ListViewUpAndDownLazyPage } from './src/main/ets/pages/list/v1/view/ListViewUpAndDownLazyPage';
import { ListViewTabsPage } from './src/main/ets/pages/list/v1/view/ListViewTabsPage';
import { ListViewSwipeActionPage } from './src/main/ets/pages/list/v1/view/ListViewSwipeActionPage';
import { ListViewStickyTopPage } from './src/main/ets/pages/list/v1/view/ListViewStickyTopPage';
import { ListViewStickyRLTopPage } from './src/main/ets/pages/list/v1/view/ListViewStickyRLTopPage';
import { ListViewStickLayoutPage } from './src/main/ets/pages/list/v1/view/ListViewStickLayoutPage';
import { ListViewSpringRatioPage } from './src/main/ets/pages/list/v1/view/ListViewSpringRatioPage';
import { ListViewSlideDeletePage } from './src/main/ets/pages/list/v1/view/ListViewSlideDeletePage';
import { ListViewRefreshPage } from './src/main/ets/pages/list/v1/view/ListViewRefreshPage';
import { ListViewRefreshHeaderFooterPage } from './src/main/ets/pages/list/v1/view/ListViewRefreshHeaderFooterPage';
import { ListViewPositioningPage } from './src/main/ets/pages/list/v1/view/ListViewPositioningPage';
import { ListViewPage } from './src/main/ets/pages/list/v1/view/ListViewPage';
import { ListViewNoSpringPage } from './src/main/ets/pages/list/v1/view/ListViewNoSpringPage';
import { ListViewNoReboundPage } from './src/main/ets/pages/list/v1/view/ListViewNoReboundPage';
import { ListViewNoDataPage } from './src/main/ets/pages/list/v1/view/ListViewNoDataPage';
import { ListViewMaxSpringPage } from './src/main/ets/pages/list/v1/view/ListViewMaxSpringPage';
import { ListViewLoadMorePage } from './src/main/ets/pages/list/v1/view/ListViewLoadMorePage';
import { ListViewLazyPage } from './src/main/ets/pages/list/v1/view/ListViewLazyPage';
import { ListViewLazyDataOperationPage } from './src/main/ets/pages/list/v1/view/ListViewLazyDataOperationPage';
import { ListViewItemGroupPage } from './src/main/ets/pages/list/v1/view/ListViewItemGroupPage';
import { ListViewItemGroupNoStickyPage } from './src/main/ets/pages/list/v1/view/ListViewItemGroupNoStickyPage';
import { ListViewItemGroupIndexPage } from './src/main/ets/pages/list/v1/view/ListViewItemGroupIndexPage';
import { ListViewHeaderPage } from './src/main/ets/pages/list/v1/view/ListViewHeaderPage';
import { ListViewHeaderAndFooterPage } from './src/main/ets/pages/list/v1/view/ListViewHeaderAndFooterPage';
import { ListViewFooterPage } from './src/main/ets/pages/list/v1/view/ListViewFooterPage';
import { ListViewFixedBottomLoadPage } from './src/main/ets/pages/list/v1/view/ListViewFixedBottomLoadPage';
import { ListViewErrorOrEmptyPage } from './src/main/ets/pages/list/v1/view/ListViewErrorOrEmptyPage';
import { ListViewEnableSpringPage } from './src/main/ets/pages/list/v1/view/ListViewEnableSpringPage';
import { ListViewDataOperationPage } from './src/main/ets/pages/list/v1/view/ListViewDataOperationPage';
import { ListViewAutoRefreshPage } from './src/main/ets/pages/list/v1/view/ListViewAutoRefreshPage';
import { ListViewAutoLoadMorePage } from './src/main/ets/pages/list/v1/view/ListViewAutoLoadMorePage';
import { ListViewArbitrarilyStickyTopPage } from './src/main/ets/pages/list/v1/view/ListViewArbitrarilyStickyTopPage';
import { ListViewAdaptivePage2 } from './src/main/ets/pages/list/v1/view/ListViewAdaptivePage2';
import { ListViewAdaptivePage } from './src/main/ets/pages/list/v1/view/ListViewAdaptivePage';
import { ListLayoutUpAndDownPage } from './src/main/ets/pages/list/v1/layout/ListLayoutUpAndDownPage';
import { ListLayoutTabsPage } from './src/main/ets/pages/list/v1/layout/ListLayoutTabsPage';
import { ListLayoutSwipeActionPage } from './src/main/ets/pages/list/v1/layout/ListLayoutSwipeActionPage';
import { ListLayoutStickyTopRefreshPage } from './src/main/ets/pages/list/v1/layout/ListLayoutStickyTopRefreshPage';
import { ListLayoutStickyTopPage } from './src/main/ets/pages/list/v1/layout/ListLayoutStickyTopPage';
import { ListLayoutStickPage } from './src/main/ets/pages/list/v1/layout/ListLayoutStickPage';
import { ListLayoutSpringRatioPage } from './src/main/ets/pages/list/v1/layout/ListLayoutSpringRatioPage';
import { ListLayoutSlideDeletePage } from './src/main/ets/pages/list/v1/layout/ListLayoutSlideDeletePage';
import { ListLayoutRefreshPage } from './src/main/ets/pages/list/v1/layout/ListLayoutRefreshPage';
import { ListLayoutRefreshHeaderFooterPage } from './src/main/ets/pages/list/v1/layout/ListLayoutRefreshHeaderFooterPage';
import { ListLayoutPositioningPage } from './src/main/ets/pages/list/v1/layout/ListLayoutPositioningPage';
import { ListLayoutPage } from './src/main/ets/pages/list/v1/layout/ListLayoutPage';
import { ListLayoutNoSpringPage } from './src/main/ets/pages/list/v1/layout/ListLayoutNoSpringPage';
import { ListLayoutNoReboundPage } from './src/main/ets/pages/list/v1/layout/ListLayoutNoReboundPage';
import { ListLayoutMaxSpringPage } from './src/main/ets/pages/list/v1/layout/ListLayoutMaxSpringPage';
import { ListLayoutLoadMorePage } from './src/main/ets/pages/list/v1/layout/ListLayoutLoadMorePage';
import { ListLayoutLazyUpAndDownPage } from './src/main/ets/pages/list/v1/layout/ListLayoutLazyUpAndDownPage';
import { ListLayoutLazyPage } from './src/main/ets/pages/list/v1/layout/ListLayoutLazyPage';
import { ListLayoutLazyDataOperationPage } from './src/main/ets/pages/list/v1/layout/ListLayoutLazyDataOperationPage';
import { ListLayoutItemGroupPage } from './src/main/ets/pages/list/v1/layout/ListLayoutItemGroupPage';
import { ListLayoutItemGroupNoStickyPage } from './src/main/ets/pages/list/v1/layout/ListLayoutItemGroupNoStickyPage';
import { ListLayoutItemGroupIndexPage } from './src/main/ets/pages/list/v1/layout/ListLayoutItemGroupIndexPage';
import { ListLayoutHeaderPage } from './src/main/ets/pages/list/v1/layout/ListLayoutHeaderPage';
import { ListLayoutHeaderAndFooterPage } from './src/main/ets/pages/list/v1/layout/ListLayoutHeaderAndFooterPage';
import { ListLayoutFooterPage } from './src/main/ets/pages/list/v1/layout/ListLayoutFooterPage';
import { ListLayoutFixedFooterPage } from './src/main/ets/pages/list/v1/layout/ListLayoutFixedFooterPage';
import { ListLayoutFixedBottomLoadPage } from './src/main/ets/pages/list/v1/layout/ListLayoutFixedBottomLoadPage';
import { ListLayoutErrorOrEmptyPage } from './src/main/ets/pages/list/v1/layout/ListLayoutErrorOrEmptyPage';
import { ListLayoutEnableSpringPage } from './src/main/ets/pages/list/v1/layout/ListLayoutEnableSpringPage';
import { ListLayoutDataOperationPage } from './src/main/ets/pages/list/v1/layout/ListLayoutDataOperationPage';
import { ListLayoutAutoRefreshPage } from './src/main/ets/pages/list/v1/layout/ListLayoutAutoRefreshPage';
import { ListLayoutAutoLoadMorePage } from './src/main/ets/pages/list/v1/layout/ListLayoutAutoLoadMorePage';
import { ListLayoutArbitrarilyStickyTopPage } from './src/main/ets/pages/list/v1/layout/ListLayoutArbitrarilyStickyTopPage';
import { ListLayoutAdaptivePage2 } from './src/main/ets/pages/list/v1/layout/ListLayoutAdaptivePage2';
import { ListLayoutAdaptivePage } from './src/main/ets/pages/list/v1/layout/ListLayoutAdaptivePage';
import { GridViewTabsPage } from './src/main/ets/pages/grid/v1/view/GridViewTabsPage';
import { GridViewStickyTopPage } from './src/main/ets/pages/grid/v1/view/GridViewStickyTopPage';
import { GridViewStickyRLTopPage } from './src/main/ets/pages/grid/v1/view/GridViewStickyRLTopPage';
import { GridViewStickLayoutViewPage } from './src/main/ets/pages/grid/v1/view/GridViewStickLayoutViewPage';
import { GridViewSpringRatioPage } from './src/main/ets/pages/grid/v1/view/GridViewSpringRatioPage';
import { GridViewRefreshPage } from './src/main/ets/pages/grid/v1/view/GridViewRefreshPage';
import { GridViewRefreshHeaderFooterPage } from './src/main/ets/pages/grid/v1/view/GridViewRefreshHeaderFooterPage';
import { GridViewRefreshAndLoadPage } from './src/main/ets/pages/grid/v1/view/GridViewRefreshAndLoadPage';
import { GridViewPositioningPage } from './src/main/ets/pages/grid/v1/view/GridViewPositioningPage';
import { GridViewPage } from './src/main/ets/pages/grid/v1/view/GridViewPage';
import { GridViewNoSpringPage } from './src/main/ets/pages/grid/v1/view/GridViewNoSpringPage';
import { GridViewNoReboundPage } from './src/main/ets/pages/grid/v1/view/GridViewNoReboundPage';
import { GridViewNoDataPage } from './src/main/ets/pages/grid/v1/view/GridViewNoDataPage';
import { GridViewMaxSpringPage } from './src/main/ets/pages/grid/v1/view/GridViewMaxSpringPage';
import { GridViewLoadMorePage } from './src/main/ets/pages/grid/v1/view/GridViewLoadMorePage';
import { GridViewLazyRefreshAndLoadPage } from './src/main/ets/pages/grid/v1/view/GridViewLazyRefreshAndLoadPage';
import { GridViewLazyPage } from './src/main/ets/pages/grid/v1/view/GridViewLazyPage';
import { GridViewHeaderPage } from './src/main/ets/pages/grid/v1/view/GridViewHeaderPage';
import { GridViewHeaderAndFooterPage } from './src/main/ets/pages/grid/v1/view/GridViewHeaderAndFooterPage';
import { GridViewFooterPage } from './src/main/ets/pages/grid/v1/view/GridViewFooterPage';
import { GridViewFixedBottomLoadPage } from './src/main/ets/pages/grid/v1/view/GridViewFixedBottomLoadPage';
import { GridViewEnableSpringPage } from './src/main/ets/pages/grid/v1/view/GridViewEnableSpringPage';
import { GridViewAutoRefreshPage } from './src/main/ets/pages/grid/v1/view/GridViewAutoRefreshPage';
import { GridViewAutoLoadMorePage } from './src/main/ets/pages/grid/v1/view/GridViewAutoLoadMorePage';
import { GridViewArbitrarilyStickyTopPage } from './src/main/ets/pages/grid/v1/view/GridViewArbitrarilyStickyTopPage';
import { GridViewAdaptiveTopPage } from './src/main/ets/pages/grid/v1/view/GridViewAdaptiveTopPage';
import { GridViewAdaptiveBottomPage } from './src/main/ets/pages/grid/v1/view/GridViewAdaptiveBottomPage';
import { GridDropPage } from './src/main/ets/pages/grid/v1/view/GridDropPage';
import { GridLayoutTabsPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutTabsPage';
import { GridLayoutStickyTopPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutStickyTopPage';
import { GridLayoutStickyRLTopPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutStickyRLTopPage';
import { GridLayoutStickLayoutViewPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutStickLayoutViewPage';
import { GridLayoutSpringRatioPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutSpringRatioPage';
import { GridLayoutRefreshPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutRefreshPage';
import { GridLayoutRefreshHeaderFooterPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutRefreshHeaderFooterPage';
import { GridLayoutRefreshAndLoadPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutRefreshAndLoadPage';
import { GridLayoutPositioningPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutPositioningPage';
import { GridLayoutPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutPage';
import { GridLayoutNoSpringPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutNoSpringPage';
import { GridLayoutNoReboundPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutNoReboundPage';
import { GridLayoutNoDataPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutNoDataPage';
import { GridLayoutMaxSpringPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutMaxSpringPage';
import { GridLayoutLoadMorePage } from './src/main/ets/pages/grid/v1/layout/GridLayoutLoadMorePage';
import { GridLayoutLazyRefreshAndLoadPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutLazyRefreshAndLoadPage';
import { GridLayoutLazyPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutLazyPage';
import { GridLayoutHeaderPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutHeaderPage';
import { GridLayoutHeaderAndFooterPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutHeaderAndFooterPage';
import { GridLayoutFooterPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutFooterPage';
import { GridLayoutFixedBottomLoadPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutFixedBottomLoadPage';
import { GridLayoutEnableSpringPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutEnableSpringPage';
import { GridLayoutAutoRefreshPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutAutoRefreshPage';
import { GridLayoutAutoLoadMorePage } from './src/main/ets/pages/grid/v1/layout/GridLayoutAutoLoadMorePage';
import { GridLayoutArbitrarilyStickyTopPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutArbitrarilyStickyTopPage';
import { GridLayoutAdaptiveTopPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutAdaptiveTopPage';
import { GridLayoutAdaptiveBottomPage } from './src/main/ets/pages/grid/v1/layout/GridLayoutAdaptiveBottomPage';
import { FlowViewTopActionBarPage } from './src/main/ets/pages/flow/v1/view/FlowViewTopActionBarPage';
import { FlowViewTabsPage } from './src/main/ets/pages/flow/v1/view/FlowViewTabsPage';
import { FlowViewStickyTopPage } from './src/main/ets/pages/flow/v1/view/FlowViewStickyTopPage';
import { FlowViewStickyTopActionBarPage } from './src/main/ets/pages/flow/v1/view/FlowViewStickyTopActionBarPage';
import { FlowViewStickyRLTopPage } from './src/main/ets/pages/flow/v1/view/FlowViewStickyRLTopPage';
import { FlowViewSpringRatioPage } from './src/main/ets/pages/flow/v1/view/FlowViewSpringRatioPage';
import { FlowViewRefreshPage } from './src/main/ets/pages/flow/v1/view/FlowViewRefreshPage';
import { FlowViewRefreshHeaderAndFooterPage } from './src/main/ets/pages/flow/v1/view/FlowViewRefreshHeaderAndFooterPage';
import { FlowViewRefreshAndLoadMorePage } from './src/main/ets/pages/flow/v1/view/FlowViewRefreshAndLoadMorePage';
import { FlowViewPositioningPage } from './src/main/ets/pages/flow/v1/view/FlowViewPositioningPage';
import { FlowViewPage } from './src/main/ets/pages/flow/v1/view/FlowViewPage';
import { FlowViewNoSpringPage } from './src/main/ets/pages/flow/v1/view/FlowViewNoSpringPage';
import { FlowViewNoReboundPage } from './src/main/ets/pages/flow/v1/view/FlowViewNoReboundPage';
import { FlowViewNoDataPage } from './src/main/ets/pages/flow/v1/view/FlowViewNoDataPage';
import { FlowViewMaxSpringPage } from './src/main/ets/pages/flow/v1/view/FlowViewMaxSpringPage';
import { FlowViewLoadMorePage } from './src/main/ets/pages/flow/v1/view/FlowViewLoadMorePage';
import { FlowViewLazyRefreshAndLoadMorePage } from './src/main/ets/pages/flow/v1/view/FlowViewLazyRefreshAndLoadMorePage';
import { FlowViewLazyPage } from './src/main/ets/pages/flow/v1/view/FlowViewLazyPage';
import { FlowViewHeaderPage } from './src/main/ets/pages/flow/v1/view/FlowViewHeaderPage';
import { FlowViewHeaderAndFooterPage } from './src/main/ets/pages/flow/v1/view/FlowViewHeaderAndFooterPage';
import { FlowViewFooterPage } from './src/main/ets/pages/flow/v1/view/FlowViewFooterPage';
import { FlowViewFixedBottomPage } from './src/main/ets/pages/flow/v1/view/FlowViewFixedBottomPage';
import { FlowViewEnableSpringPage } from './src/main/ets/pages/flow/v1/view/FlowViewEnableSpringPage';
import { FlowViewAutoRefreshPage } from './src/main/ets/pages/flow/v1/view/FlowViewAutoRefreshPage';
import { FlowViewAutoLoadMorePage } from './src/main/ets/pages/flow/v1/view/FlowViewAutoLoadMorePage';
import { FlowViewArbitrarilyStickyTopPage } from './src/main/ets/pages/flow/v1/view/FlowViewArbitrarilyStickyTopPage';
import { FlowViewAdaptiveTopPage } from './src/main/ets/pages/flow/v1/view/FlowViewAdaptiveTopPage';
import { FlowViewAdaptiveBottomPage } from './src/main/ets/pages/flow/v1/view/FlowViewAdaptiveBottomPage';
import { FlowLayoutTopActionBarPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutTopActionBarPage';
import { FlowLayoutStickyTopPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutStickyTopPage';
import { FlowLayoutStickyRLTopPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutStickyRLTopPage';
import { FlowLayoutSpringRatioPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutSpringRatioPage';
import { FlowLayoutRefreshPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutRefreshPage';
import { FlowLayoutRefreshHeaderAndFooterPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutRefreshHeaderAndFooterPage';
import { FlowLayoutRefreshAndLoadMorePage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutRefreshAndLoadMorePage';
import { FlowLayoutPositioningPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutPositioningPage';
import { FlowLayoutPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutPage';
import { FlowLayoutNoSpringPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutNoSpringPage';
import { FlowLayoutNoReboundPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutNoReboundPage';
import { FlowLayoutNoDataPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutNoDataPage';
import { FlowLayoutMaxSpringPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutMaxSpringPage';
import { FlowLayoutLoadMorePage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutLoadMorePage';
import { FlowLayoutLazyRefreshAndLoadMorePage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutLazyRefreshAndLoadMorePage';
import { FlowLayoutLazyPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutLazyPage';
import { FlowLayoutHeaderPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutHeaderPage';
import { FlowLayoutHeaderAndFooterPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutHeaderAndFooterPage';
import { FlowLayoutFooterPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutFooterPage';
import { FlowLayoutFixedBottomPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutFixedBottomPage';
import { FlowLayoutEnableSpringPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutEnableSpringPage';
import { FlowLayoutAutoLoadMorePage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutAutoLoadMorePage';
import { FlowLayoutAdaptiveTopPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutAdaptiveTopPage';
import { FlowLayoutAdaptiveBottomPage } from './src/main/ets/pages/flow/v1/layout/FlowLayoutAdaptiveBottomPage';
import { SecondFloorExample2 } from './src/main/ets/pages/floor/v1/example2/SecondFloorExample2';
import { SecondFloorExample } from './src/main/ets/pages/floor/v1/example/SecondFloorExample';
import { SecondFloorPage } from './src/main/ets/pages/floor/v1/SecondFloorPage';
import { RouterConfig,routerGetBuilderType, routerInitBuilder,NavDestinationView } from '@abner/router';

/**
 * AUTHOR:AbnerMing
 * INTRODUCE:动态配置路径
 * */
function importPath(builderName: string) {
  switch (builderName) {
    case "example_ListIndex":
      import("./src/main/ets/pages/list/ListIndex")
      break
    case "example_GridIndex":
      import("./src/main/ets/pages/grid/GridIndex")
      break
    case "example_FlowIndex":
      import("./src/main/ets/pages/flow/FlowIndex")
      break
    case "example_Rv1WebViewPage":
      import("./src/main/ets/pages/rv/v1/Rv1WebViewPage")
      break
    case "example_Rv1WaterFlowUpAndDownPage":
      import("./src/main/ets/pages/rv/v1/Rv1WaterFlowUpAndDownPage")
      break
    case "example_Rv1RefreshUpAndDownPage":
      import("./src/main/ets/pages/rv/v1/Rv1RefreshUpAndDownPage")
      break
    case "example_Rv1RefreshScrollPage":
      import("./src/main/ets/pages/rv/v1/Rv1RefreshScrollPage")
      break
    case "example_Rv1RefreshPointPage":
      import("./src/main/ets/pages/rv/v1/Rv1RefreshPointPage")
      break
    case "example_Rv1RefreshImmersivePage":
      import("./src/main/ets/pages/rv/v1/Rv1RefreshImmersivePage")
      break
    case "example_Rv1RefreshHeaderAndFooterPage":
      import("./src/main/ets/pages/rv/v1/Rv1RefreshHeaderAndFooterPage")
      break
    case "example_Rv1NoScrollSpringPage":
      import("./src/main/ets/pages/rv/v1/Rv1NoScrollSpringPage")
      break
    case "example_Rv1MultiViewPage":
      import("./src/main/ets/pages/rv/v1/Rv1MultiViewPage")
      break
    case "example_Rv1MaxScrollSpringPage":
      import("./src/main/ets/pages/rv/v1/Rv1MaxScrollSpringPage")
      break
    case "example_Rv1LoadDataSpringBackPage":
      import("./src/main/ets/pages/rv/v1/Rv1LoadDataSpringBackPage")
      break
    case "example_Rv1ListUpAndDownPage":
      import("./src/main/ets/pages/rv/v1/Rv1ListUpAndDownPage")
      break
    case "example_Rv1LazyDataOperationPage":
      import("./src/main/ets/pages/rv/v1/Rv1LazyDataOperationPage")
      break
    case "example_Rv1Index":
      import("./src/main/ets/pages/rv/v1/Rv1Index")
      break
    case "example_Rv1GridUpAndDownPage":
      import("./src/main/ets/pages/rv/v1/Rv1GridUpAndDownPage")
      break
    case "example_Rv1FooterNothingPage":
      import("./src/main/ets/pages/rv/v1/Rv1FooterNothingPage")
      break
    case "example_Rv1FixedFooterPage":
      import("./src/main/ets/pages/rv/v1/Rv1FixedFooterPage")
      break
    case "example_Rv1AutoRefreshPage":
      import("./src/main/ets/pages/rv/v1/Rv1AutoRefreshPage")
      break
    case "example_Rv1AutoListUpAndDownPage":
      import("./src/main/ets/pages/rv/v1/Rv1AutoListUpAndDownPage")
      break
    case "example_Rv1AdaptiveHeightPage":
      import("./src/main/ets/pages/rv/v1/Rv1AdaptiveHeightPage")
      break
    case "example_LitheV1WebViewPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1WebViewPage")
      break
    case "example_LitheV1WaterFlowUpAndDownPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1WaterFlowUpAndDownPage")
      break
    case "example_LitheV1RefreshUpAndDownPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1RefreshUpAndDownPage")
      break
    case "example_LitheV1RefreshScrollPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1RefreshScrollPage")
      break
    case "example_LitheV1RefreshPointPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1RefreshPointPage")
      break
    case "example_LitheV1RefreshImmersivePage":
      import("./src/main/ets/pages/lithe/v1/LitheV1RefreshImmersivePage")
      break
    case "example_LitheV1RefreshHeaderAndFooterPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1RefreshHeaderAndFooterPage")
      break
    case "example_LitheV1NoScrollSpringPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1NoScrollSpringPage")
      break
    case "example_LitheV1MultiViewPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1MultiViewPage")
      break
    case "example_LitheV1LoadDataSpringBackPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1LoadDataSpringBackPage")
      break
    case "example_LitheV1ListUpAndDownPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1ListUpAndDownPage")
      break
    case "example_LitheV1ListMaxSpringPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1ListMaxSpringPage")
      break
    case "example_LitheV1LazyDataOperationPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1LazyDataOperationPage")
      break
    case "example_LitheV1LayoutHeaderPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1LayoutHeaderPage")
      break
    case "example_LitheV1Index":
      import("./src/main/ets/pages/lithe/v1/LitheV1Index")
      break
    case "example_LitheV1GridUpAndDownPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1GridUpAndDownPage")
      break
    case "example_LitheV1FooterNothingPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1FooterNothingPage")
      break
    case "example_LitheV1FixedFooterPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1FixedFooterPage")
      break
    case "example_LitheV1AutoRefreshPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1AutoRefreshPage")
      break
    case "example_LitheV1AutoListUpAndDownPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1AutoListUpAndDownPage")
      break
    case "example_LitheV1AdaptiveHeightPage":
      import("./src/main/ets/pages/lithe/v1/LitheV1AdaptiveHeightPage")
      break
    case "example_ListViewUpAndDownPage":
      import("./src/main/ets/pages/list/v1/view/ListViewUpAndDownPage")
      break
    case "example_ListViewUpAndDownLazyPage":
      import("./src/main/ets/pages/list/v1/view/ListViewUpAndDownLazyPage")
      break
    case "example_ListViewTabsPage":
      import("./src/main/ets/pages/list/v1/view/ListViewTabsPage")
      break
    case "example_ListViewSwipeActionPage":
      import("./src/main/ets/pages/list/v1/view/ListViewSwipeActionPage")
      break
    case "example_ListViewStickyTopPage":
      import("./src/main/ets/pages/list/v1/view/ListViewStickyTopPage")
      break
    case "example_ListViewStickyRLTopPage":
      import("./src/main/ets/pages/list/v1/view/ListViewStickyRLTopPage")
      break
    case "example_ListViewStickLayoutPage":
      import("./src/main/ets/pages/list/v1/view/ListViewStickLayoutPage")
      break
    case "example_ListViewSpringRatioPage":
      import("./src/main/ets/pages/list/v1/view/ListViewSpringRatioPage")
      break
    case "example_ListViewSlideDeletePage":
      import("./src/main/ets/pages/list/v1/view/ListViewSlideDeletePage")
      break
    case "example_ListViewRefreshPage":
      import("./src/main/ets/pages/list/v1/view/ListViewRefreshPage")
      break
    case "example_ListViewRefreshHeaderFooterPage":
      import("./src/main/ets/pages/list/v1/view/ListViewRefreshHeaderFooterPage")
      break
    case "example_ListViewPositioningPage":
      import("./src/main/ets/pages/list/v1/view/ListViewPositioningPage")
      break
    case "example_ListViewPage":
      import("./src/main/ets/pages/list/v1/view/ListViewPage")
      break
    case "example_ListViewNoSpringPage":
      import("./src/main/ets/pages/list/v1/view/ListViewNoSpringPage")
      break
    case "example_ListViewNoReboundPage":
      import("./src/main/ets/pages/list/v1/view/ListViewNoReboundPage")
      break
    case "example_ListViewNoDataPage":
      import("./src/main/ets/pages/list/v1/view/ListViewNoDataPage")
      break
    case "example_ListViewMaxSpringPage":
      import("./src/main/ets/pages/list/v1/view/ListViewMaxSpringPage")
      break
    case "example_ListViewLoadMorePage":
      import("./src/main/ets/pages/list/v1/view/ListViewLoadMorePage")
      break
    case "example_ListViewLazyPage":
      import("./src/main/ets/pages/list/v1/view/ListViewLazyPage")
      break
    case "example_ListViewLazyDataOperationPage":
      import("./src/main/ets/pages/list/v1/view/ListViewLazyDataOperationPage")
      break
    case "example_ListViewItemGroupPage":
      import("./src/main/ets/pages/list/v1/view/ListViewItemGroupPage")
      break
    case "example_ListViewItemGroupNoStickyPage":
      import("./src/main/ets/pages/list/v1/view/ListViewItemGroupNoStickyPage")
      break
    case "example_ListViewItemGroupIndexPage":
      import("./src/main/ets/pages/list/v1/view/ListViewItemGroupIndexPage")
      break
    case "example_ListViewHeaderPage":
      import("./src/main/ets/pages/list/v1/view/ListViewHeaderPage")
      break
    case "example_ListViewHeaderAndFooterPage":
      import("./src/main/ets/pages/list/v1/view/ListViewHeaderAndFooterPage")
      break
    case "example_ListViewFooterPage":
      import("./src/main/ets/pages/list/v1/view/ListViewFooterPage")
      break
    case "example_ListViewFixedBottomLoadPage":
      import("./src/main/ets/pages/list/v1/view/ListViewFixedBottomLoadPage")
      break
    case "example_ListViewErrorOrEmptyPage":
      import("./src/main/ets/pages/list/v1/view/ListViewErrorOrEmptyPage")
      break
    case "example_ListViewEnableSpringPage":
      import("./src/main/ets/pages/list/v1/view/ListViewEnableSpringPage")
      break
    case "example_ListViewDataOperationPage":
      import("./src/main/ets/pages/list/v1/view/ListViewDataOperationPage")
      break
    case "example_ListViewAutoRefreshPage":
      import("./src/main/ets/pages/list/v1/view/ListViewAutoRefreshPage")
      break
    case "example_ListViewAutoLoadMorePage":
      import("./src/main/ets/pages/list/v1/view/ListViewAutoLoadMorePage")
      break
    case "example_ListViewArbitrarilyStickyTopPage":
      import("./src/main/ets/pages/list/v1/view/ListViewArbitrarilyStickyTopPage")
      break
    case "example_ListViewAdaptivePage2":
      import("./src/main/ets/pages/list/v1/view/ListViewAdaptivePage2")
      break
    case "example_ListViewAdaptivePage":
      import("./src/main/ets/pages/list/v1/view/ListViewAdaptivePage")
      break
    case "example_ListLayoutUpAndDownPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutUpAndDownPage")
      break
    case "example_ListLayoutTabsPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutTabsPage")
      break
    case "example_ListLayoutSwipeActionPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutSwipeActionPage")
      break
    case "example_ListLayoutStickyTopRefreshPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutStickyTopRefreshPage")
      break
    case "example_ListLayoutStickyTopPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutStickyTopPage")
      break
    case "example_ListLayoutStickPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutStickPage")
      break
    case "example_ListLayoutSpringRatioPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutSpringRatioPage")
      break
    case "example_ListLayoutSlideDeletePage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutSlideDeletePage")
      break
    case "example_ListLayoutRefreshPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutRefreshPage")
      break
    case "example_ListLayoutRefreshHeaderFooterPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutRefreshHeaderFooterPage")
      break
    case "example_ListLayoutPositioningPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutPositioningPage")
      break
    case "example_ListLayoutPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutPage")
      break
    case "example_ListLayoutNoSpringPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutNoSpringPage")
      break
    case "example_ListLayoutNoReboundPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutNoReboundPage")
      break
    case "example_ListLayoutMaxSpringPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutMaxSpringPage")
      break
    case "example_ListLayoutLoadMorePage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutLoadMorePage")
      break
    case "example_ListLayoutLazyUpAndDownPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutLazyUpAndDownPage")
      break
    case "example_ListLayoutLazyPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutLazyPage")
      break
    case "example_ListLayoutLazyDataOperationPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutLazyDataOperationPage")
      break
    case "example_ListLayoutItemGroupPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutItemGroupPage")
      break
    case "example_ListLayoutItemGroupNoStickyPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutItemGroupNoStickyPage")
      break
    case "example_ListLayoutItemGroupIndexPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutItemGroupIndexPage")
      break
    case "example_ListLayoutHeaderPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutHeaderPage")
      break
    case "example_ListLayoutHeaderAndFooterPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutHeaderAndFooterPage")
      break
    case "example_ListLayoutFooterPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutFooterPage")
      break
    case "example_ListLayoutFixedFooterPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutFixedFooterPage")
      break
    case "example_ListLayoutFixedBottomLoadPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutFixedBottomLoadPage")
      break
    case "example_ListLayoutErrorOrEmptyPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutErrorOrEmptyPage")
      break
    case "example_ListLayoutEnableSpringPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutEnableSpringPage")
      break
    case "example_ListLayoutDataOperationPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutDataOperationPage")
      break
    case "example_ListLayoutAutoRefreshPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutAutoRefreshPage")
      break
    case "example_ListLayoutAutoLoadMorePage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutAutoLoadMorePage")
      break
    case "example_ListLayoutArbitrarilyStickyTopPage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutArbitrarilyStickyTopPage")
      break
    case "example_ListLayoutAdaptivePage2":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutAdaptivePage2")
      break
    case "example_ListLayoutAdaptivePage":
      import("./src/main/ets/pages/list/v1/layout/ListLayoutAdaptivePage")
      break
    case "example_GridViewTabsPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewTabsPage")
      break
    case "example_GridViewStickyTopPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewStickyTopPage")
      break
    case "example_GridViewStickyRLTopPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewStickyRLTopPage")
      break
    case "example_GridViewStickLayoutViewPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewStickLayoutViewPage")
      break
    case "example_GridViewSpringRatioPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewSpringRatioPage")
      break
    case "example_GridViewRefreshPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewRefreshPage")
      break
    case "example_GridViewRefreshHeaderFooterPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewRefreshHeaderFooterPage")
      break
    case "example_GridViewRefreshAndLoadPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewRefreshAndLoadPage")
      break
    case "example_GridViewPositioningPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewPositioningPage")
      break
    case "example_GridViewPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewPage")
      break
    case "example_GridViewNoSpringPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewNoSpringPage")
      break
    case "example_GridViewNoReboundPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewNoReboundPage")
      break
    case "example_GridViewNoDataPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewNoDataPage")
      break
    case "example_GridViewMaxSpringPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewMaxSpringPage")
      break
    case "example_GridViewLoadMorePage":
      import("./src/main/ets/pages/grid/v1/view/GridViewLoadMorePage")
      break
    case "example_GridViewLazyRefreshAndLoadPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewLazyRefreshAndLoadPage")
      break
    case "example_GridViewLazyPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewLazyPage")
      break
    case "example_GridViewHeaderPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewHeaderPage")
      break
    case "example_GridViewHeaderAndFooterPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewHeaderAndFooterPage")
      break
    case "example_GridViewFooterPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewFooterPage")
      break
    case "example_GridViewFixedBottomLoadPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewFixedBottomLoadPage")
      break
    case "example_GridViewEnableSpringPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewEnableSpringPage")
      break
    case "example_GridViewAutoRefreshPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewAutoRefreshPage")
      break
    case "example_GridViewAutoLoadMorePage":
      import("./src/main/ets/pages/grid/v1/view/GridViewAutoLoadMorePage")
      break
    case "example_GridViewArbitrarilyStickyTopPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewArbitrarilyStickyTopPage")
      break
    case "example_GridViewAdaptiveTopPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewAdaptiveTopPage")
      break
    case "example_GridViewAdaptiveBottomPage":
      import("./src/main/ets/pages/grid/v1/view/GridViewAdaptiveBottomPage")
      break
    case "example_GridDropPage":
      import("./src/main/ets/pages/grid/v1/view/GridDropPage")
      break
    case "example_GridLayoutTabsPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutTabsPage")
      break
    case "example_GridLayoutStickyTopPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutStickyTopPage")
      break
    case "example_GridLayoutStickyRLTopPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutStickyRLTopPage")
      break
    case "example_GridLayoutStickLayoutViewPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutStickLayoutViewPage")
      break
    case "example_GridLayoutSpringRatioPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutSpringRatioPage")
      break
    case "example_GridLayoutRefreshPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutRefreshPage")
      break
    case "example_GridLayoutRefreshHeaderFooterPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutRefreshHeaderFooterPage")
      break
    case "example_GridLayoutRefreshAndLoadPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutRefreshAndLoadPage")
      break
    case "example_GridLayoutPositioningPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutPositioningPage")
      break
    case "example_GridLayoutPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutPage")
      break
    case "example_GridLayoutNoSpringPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutNoSpringPage")
      break
    case "example_GridLayoutNoReboundPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutNoReboundPage")
      break
    case "example_GridLayoutNoDataPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutNoDataPage")
      break
    case "example_GridLayoutMaxSpringPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutMaxSpringPage")
      break
    case "example_GridLayoutLoadMorePage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutLoadMorePage")
      break
    case "example_GridLayoutLazyRefreshAndLoadPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutLazyRefreshAndLoadPage")
      break
    case "example_GridLayoutLazyPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutLazyPage")
      break
    case "example_GridLayoutHeaderPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutHeaderPage")
      break
    case "example_GridLayoutHeaderAndFooterPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutHeaderAndFooterPage")
      break
    case "example_GridLayoutFooterPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutFooterPage")
      break
    case "example_GridLayoutFixedBottomLoadPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutFixedBottomLoadPage")
      break
    case "example_GridLayoutEnableSpringPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutEnableSpringPage")
      break
    case "example_GridLayoutAutoRefreshPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutAutoRefreshPage")
      break
    case "example_GridLayoutAutoLoadMorePage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutAutoLoadMorePage")
      break
    case "example_GridLayoutArbitrarilyStickyTopPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutArbitrarilyStickyTopPage")
      break
    case "example_GridLayoutAdaptiveTopPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutAdaptiveTopPage")
      break
    case "example_GridLayoutAdaptiveBottomPage":
      import("./src/main/ets/pages/grid/v1/layout/GridLayoutAdaptiveBottomPage")
      break
    case "example_FlowViewTopActionBarPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewTopActionBarPage")
      break
    case "example_FlowViewTabsPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewTabsPage")
      break
    case "example_FlowViewStickyTopPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewStickyTopPage")
      break
    case "example_FlowViewStickyTopActionBarPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewStickyTopActionBarPage")
      break
    case "example_FlowViewStickyRLTopPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewStickyRLTopPage")
      break
    case "example_FlowViewSpringRatioPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewSpringRatioPage")
      break
    case "example_FlowViewRefreshPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewRefreshPage")
      break
    case "example_FlowViewRefreshHeaderAndFooterPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewRefreshHeaderAndFooterPage")
      break
    case "example_FlowViewRefreshAndLoadMorePage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewRefreshAndLoadMorePage")
      break
    case "example_FlowViewPositioningPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewPositioningPage")
      break
    case "example_FlowViewPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewPage")
      break
    case "example_FlowViewNoSpringPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewNoSpringPage")
      break
    case "example_FlowViewNoReboundPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewNoReboundPage")
      break
    case "example_FlowViewNoDataPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewNoDataPage")
      break
    case "example_FlowViewMaxSpringPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewMaxSpringPage")
      break
    case "example_FlowViewLoadMorePage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewLoadMorePage")
      break
    case "example_FlowViewLazyRefreshAndLoadMorePage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewLazyRefreshAndLoadMorePage")
      break
    case "example_FlowViewLazyPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewLazyPage")
      break
    case "example_FlowViewHeaderPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewHeaderPage")
      break
    case "example_FlowViewHeaderAndFooterPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewHeaderAndFooterPage")
      break
    case "example_FlowViewFooterPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewFooterPage")
      break
    case "example_FlowViewFixedBottomPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewFixedBottomPage")
      break
    case "example_FlowViewEnableSpringPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewEnableSpringPage")
      break
    case "example_FlowViewAutoRefreshPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewAutoRefreshPage")
      break
    case "example_FlowViewAutoLoadMorePage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewAutoLoadMorePage")
      break
    case "example_FlowViewArbitrarilyStickyTopPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewArbitrarilyStickyTopPage")
      break
    case "example_FlowViewAdaptiveTopPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewAdaptiveTopPage")
      break
    case "example_FlowViewAdaptiveBottomPage":
      import("./src/main/ets/pages/flow/v1/view/FlowViewAdaptiveBottomPage")
      break
    case "example_FlowLayoutTopActionBarPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutTopActionBarPage")
      break
    case "example_FlowLayoutStickyTopPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutStickyTopPage")
      break
    case "example_FlowLayoutStickyRLTopPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutStickyRLTopPage")
      break
    case "example_FlowLayoutSpringRatioPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutSpringRatioPage")
      break
    case "example_FlowLayoutRefreshPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutRefreshPage")
      break
    case "example_FlowLayoutRefreshHeaderAndFooterPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutRefreshHeaderAndFooterPage")
      break
    case "example_FlowLayoutRefreshAndLoadMorePage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutRefreshAndLoadMorePage")
      break
    case "example_FlowLayoutPositioningPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutPositioningPage")
      break
    case "example_FlowLayoutPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutPage")
      break
    case "example_FlowLayoutNoSpringPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutNoSpringPage")
      break
    case "example_FlowLayoutNoReboundPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutNoReboundPage")
      break
    case "example_FlowLayoutNoDataPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutNoDataPage")
      break
    case "example_FlowLayoutMaxSpringPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutMaxSpringPage")
      break
    case "example_FlowLayoutLoadMorePage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutLoadMorePage")
      break
    case "example_FlowLayoutLazyRefreshAndLoadMorePage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutLazyRefreshAndLoadMorePage")
      break
    case "example_FlowLayoutLazyPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutLazyPage")
      break
    case "example_FlowLayoutHeaderPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutHeaderPage")
      break
    case "example_FlowLayoutHeaderAndFooterPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutHeaderAndFooterPage")
      break
    case "example_FlowLayoutFooterPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutFooterPage")
      break
    case "example_FlowLayoutFixedBottomPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutFixedBottomPage")
      break
    case "example_FlowLayoutEnableSpringPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutEnableSpringPage")
      break
    case "example_FlowLayoutAutoLoadMorePage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutAutoLoadMorePage")
      break
    case "example_FlowLayoutAdaptiveTopPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutAdaptiveTopPage")
      break
    case "example_FlowLayoutAdaptiveBottomPage":
      import("./src/main/ets/pages/flow/v1/layout/FlowLayoutAdaptiveBottomPage")
      break
    case "example_SecondFloorExample2":
      import("./src/main/ets/pages/floor/v1/example2/SecondFloorExample2")
      break
    case "example_SecondFloorExample":
      import("./src/main/ets/pages/floor/v1/example/SecondFloorExample")
      break
    case "example_SecondFloorPage":
      import("./src/main/ets/pages/floor/v1/SecondFloorPage")
      break

  }
}

/**
 * AUTHOR:AbnerMing
 * INTRODUCE:动态配置组件
 * */
@Builder
export function viewBuilder(params?:Object) {
  NavDestinationView() {
    if (routerGetBuilderType() == "example_ListIndex") {
      ListIndex()
    } else 
    if (routerGetBuilderType() == "example_GridIndex") {
      GridIndex()
    } else 
    if (routerGetBuilderType() == "example_FlowIndex") {
      FlowIndex()
    } else 
    if (routerGetBuilderType() == "example_Rv1WebViewPage") {
      Rv1WebViewPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1WaterFlowUpAndDownPage") {
      Rv1WaterFlowUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1RefreshUpAndDownPage") {
      Rv1RefreshUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1RefreshScrollPage") {
      Rv1RefreshScrollPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1RefreshPointPage") {
      Rv1RefreshPointPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1RefreshImmersivePage") {
      Rv1RefreshImmersivePage()
    } else 
    if (routerGetBuilderType() == "example_Rv1RefreshHeaderAndFooterPage") {
      Rv1RefreshHeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1NoScrollSpringPage") {
      Rv1NoScrollSpringPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1MultiViewPage") {
      Rv1MultiViewPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1MaxScrollSpringPage") {
      Rv1MaxScrollSpringPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1LoadDataSpringBackPage") {
      Rv1LoadDataSpringBackPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1ListUpAndDownPage") {
      Rv1ListUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1LazyDataOperationPage") {
      Rv1LazyDataOperationPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1Index") {
      Rv1Index()
    } else 
    if (routerGetBuilderType() == "example_Rv1GridUpAndDownPage") {
      Rv1GridUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1FooterNothingPage") {
      Rv1FooterNothingPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1FixedFooterPage") {
      Rv1FixedFooterPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1AutoRefreshPage") {
      Rv1AutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1AutoListUpAndDownPage") {
      Rv1AutoListUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_Rv1AdaptiveHeightPage") {
      Rv1AdaptiveHeightPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1WebViewPage") {
      LitheV1WebViewPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1WaterFlowUpAndDownPage") {
      LitheV1WaterFlowUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1RefreshUpAndDownPage") {
      LitheV1RefreshUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1RefreshScrollPage") {
      LitheV1RefreshScrollPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1RefreshPointPage") {
      LitheV1RefreshPointPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1RefreshImmersivePage") {
      LitheV1RefreshImmersivePage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1RefreshHeaderAndFooterPage") {
      LitheV1RefreshHeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1NoScrollSpringPage") {
      LitheV1NoScrollSpringPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1MultiViewPage") {
      LitheV1MultiViewPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1LoadDataSpringBackPage") {
      LitheV1LoadDataSpringBackPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1ListUpAndDownPage") {
      LitheV1ListUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1ListMaxSpringPage") {
      LitheV1ListMaxSpringPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1LazyDataOperationPage") {
      LitheV1LazyDataOperationPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1LayoutHeaderPage") {
      LitheV1LayoutHeaderPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1Index") {
      LitheV1Index()
    } else 
    if (routerGetBuilderType() == "example_LitheV1GridUpAndDownPage") {
      LitheV1GridUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1FooterNothingPage") {
      LitheV1FooterNothingPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1FixedFooterPage") {
      LitheV1FixedFooterPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1AutoRefreshPage") {
      LitheV1AutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1AutoListUpAndDownPage") {
      LitheV1AutoListUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_LitheV1AdaptiveHeightPage") {
      LitheV1AdaptiveHeightPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewUpAndDownPage") {
      ListViewUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewUpAndDownLazyPage") {
      ListViewUpAndDownLazyPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewTabsPage") {
      ListViewTabsPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewSwipeActionPage") {
      ListViewSwipeActionPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewStickyTopPage") {
      ListViewStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewStickyRLTopPage") {
      ListViewStickyRLTopPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewStickLayoutPage") {
      ListViewStickLayoutPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewSpringRatioPage") {
      ListViewSpringRatioPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewSlideDeletePage") {
      ListViewSlideDeletePage()
    } else 
    if (routerGetBuilderType() == "example_ListViewRefreshPage") {
      ListViewRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewRefreshHeaderFooterPage") {
      ListViewRefreshHeaderFooterPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewPositioningPage") {
      ListViewPositioningPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewPage") {
      ListViewPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewNoSpringPage") {
      ListViewNoSpringPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewNoReboundPage") {
      ListViewNoReboundPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewNoDataPage") {
      ListViewNoDataPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewMaxSpringPage") {
      ListViewMaxSpringPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewLoadMorePage") {
      ListViewLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_ListViewLazyPage") {
      ListViewLazyPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewLazyDataOperationPage") {
      ListViewLazyDataOperationPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewItemGroupPage") {
      ListViewItemGroupPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewItemGroupNoStickyPage") {
      ListViewItemGroupNoStickyPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewItemGroupIndexPage") {
      ListViewItemGroupIndexPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewHeaderPage") {
      ListViewHeaderPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewHeaderAndFooterPage") {
      ListViewHeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewFooterPage") {
      ListViewFooterPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewFixedBottomLoadPage") {
      ListViewFixedBottomLoadPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewErrorOrEmptyPage") {
      ListViewErrorOrEmptyPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewEnableSpringPage") {
      ListViewEnableSpringPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewDataOperationPage") {
      ListViewDataOperationPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewAutoRefreshPage") {
      ListViewAutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewAutoLoadMorePage") {
      ListViewAutoLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_ListViewArbitrarilyStickyTopPage") {
      ListViewArbitrarilyStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_ListViewAdaptivePage2") {
      ListViewAdaptivePage2()
    } else 
    if (routerGetBuilderType() == "example_ListViewAdaptivePage") {
      ListViewAdaptivePage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutUpAndDownPage") {
      ListLayoutUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutTabsPage") {
      ListLayoutTabsPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutSwipeActionPage") {
      ListLayoutSwipeActionPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutStickyTopRefreshPage") {
      ListLayoutStickyTopRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutStickyTopPage") {
      ListLayoutStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutStickPage") {
      ListLayoutStickPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutSpringRatioPage") {
      ListLayoutSpringRatioPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutSlideDeletePage") {
      ListLayoutSlideDeletePage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutRefreshPage") {
      ListLayoutRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutRefreshHeaderFooterPage") {
      ListLayoutRefreshHeaderFooterPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutPositioningPage") {
      ListLayoutPositioningPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutPage") {
      ListLayoutPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutNoSpringPage") {
      ListLayoutNoSpringPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutNoReboundPage") {
      ListLayoutNoReboundPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutMaxSpringPage") {
      ListLayoutMaxSpringPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutLoadMorePage") {
      ListLayoutLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutLazyUpAndDownPage") {
      ListLayoutLazyUpAndDownPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutLazyPage") {
      ListLayoutLazyPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutLazyDataOperationPage") {
      ListLayoutLazyDataOperationPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutItemGroupPage") {
      ListLayoutItemGroupPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutItemGroupNoStickyPage") {
      ListLayoutItemGroupNoStickyPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutItemGroupIndexPage") {
      ListLayoutItemGroupIndexPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutHeaderPage") {
      ListLayoutHeaderPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutHeaderAndFooterPage") {
      ListLayoutHeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutFooterPage") {
      ListLayoutFooterPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutFixedFooterPage") {
      ListLayoutFixedFooterPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutFixedBottomLoadPage") {
      ListLayoutFixedBottomLoadPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutErrorOrEmptyPage") {
      ListLayoutErrorOrEmptyPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutEnableSpringPage") {
      ListLayoutEnableSpringPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutDataOperationPage") {
      ListLayoutDataOperationPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutAutoRefreshPage") {
      ListLayoutAutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutAutoLoadMorePage") {
      ListLayoutAutoLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutArbitrarilyStickyTopPage") {
      ListLayoutArbitrarilyStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutAdaptivePage2") {
      ListLayoutAdaptivePage2()
    } else 
    if (routerGetBuilderType() == "example_ListLayoutAdaptivePage") {
      ListLayoutAdaptivePage()
    } else 
    if (routerGetBuilderType() == "example_GridViewTabsPage") {
      GridViewTabsPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewStickyTopPage") {
      GridViewStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewStickyRLTopPage") {
      GridViewStickyRLTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewStickLayoutViewPage") {
      GridViewStickLayoutViewPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewSpringRatioPage") {
      GridViewSpringRatioPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewRefreshPage") {
      GridViewRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewRefreshHeaderFooterPage") {
      GridViewRefreshHeaderFooterPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewRefreshAndLoadPage") {
      GridViewRefreshAndLoadPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewPositioningPage") {
      GridViewPositioningPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewPage") {
      GridViewPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewNoSpringPage") {
      GridViewNoSpringPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewNoReboundPage") {
      GridViewNoReboundPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewNoDataPage") {
      GridViewNoDataPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewMaxSpringPage") {
      GridViewMaxSpringPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewLoadMorePage") {
      GridViewLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_GridViewLazyRefreshAndLoadPage") {
      GridViewLazyRefreshAndLoadPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewLazyPage") {
      GridViewLazyPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewHeaderPage") {
      GridViewHeaderPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewHeaderAndFooterPage") {
      GridViewHeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewFooterPage") {
      GridViewFooterPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewFixedBottomLoadPage") {
      GridViewFixedBottomLoadPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewEnableSpringPage") {
      GridViewEnableSpringPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewAutoRefreshPage") {
      GridViewAutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewAutoLoadMorePage") {
      GridViewAutoLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_GridViewArbitrarilyStickyTopPage") {
      GridViewArbitrarilyStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewAdaptiveTopPage") {
      GridViewAdaptiveTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridViewAdaptiveBottomPage") {
      GridViewAdaptiveBottomPage()
    } else 
    if (routerGetBuilderType() == "example_GridDropPage") {
      GridDropPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutTabsPage") {
      GridLayoutTabsPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutStickyTopPage") {
      GridLayoutStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutStickyRLTopPage") {
      GridLayoutStickyRLTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutStickLayoutViewPage") {
      GridLayoutStickLayoutViewPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutSpringRatioPage") {
      GridLayoutSpringRatioPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutRefreshPage") {
      GridLayoutRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutRefreshHeaderFooterPage") {
      GridLayoutRefreshHeaderFooterPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutRefreshAndLoadPage") {
      GridLayoutRefreshAndLoadPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutPositioningPage") {
      GridLayoutPositioningPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutPage") {
      GridLayoutPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutNoSpringPage") {
      GridLayoutNoSpringPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutNoReboundPage") {
      GridLayoutNoReboundPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutNoDataPage") {
      GridLayoutNoDataPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutMaxSpringPage") {
      GridLayoutMaxSpringPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutLoadMorePage") {
      GridLayoutLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutLazyRefreshAndLoadPage") {
      GridLayoutLazyRefreshAndLoadPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutLazyPage") {
      GridLayoutLazyPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutHeaderPage") {
      GridLayoutHeaderPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutHeaderAndFooterPage") {
      GridLayoutHeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutFooterPage") {
      GridLayoutFooterPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutFixedBottomLoadPage") {
      GridLayoutFixedBottomLoadPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutEnableSpringPage") {
      GridLayoutEnableSpringPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutAutoRefreshPage") {
      GridLayoutAutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutAutoLoadMorePage") {
      GridLayoutAutoLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutArbitrarilyStickyTopPage") {
      GridLayoutArbitrarilyStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutAdaptiveTopPage") {
      GridLayoutAdaptiveTopPage()
    } else 
    if (routerGetBuilderType() == "example_GridLayoutAdaptiveBottomPage") {
      GridLayoutAdaptiveBottomPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewTopActionBarPage") {
      FlowViewTopActionBarPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewTabsPage") {
      FlowViewTabsPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewStickyTopPage") {
      FlowViewStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewStickyTopActionBarPage") {
      FlowViewStickyTopActionBarPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewStickyRLTopPage") {
      FlowViewStickyRLTopPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewSpringRatioPage") {
      FlowViewSpringRatioPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewRefreshPage") {
      FlowViewRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewRefreshHeaderAndFooterPage") {
      FlowViewRefreshHeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewRefreshAndLoadMorePage") {
      FlowViewRefreshAndLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewPositioningPage") {
      FlowViewPositioningPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewPage") {
      FlowViewPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewNoSpringPage") {
      FlowViewNoSpringPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewNoReboundPage") {
      FlowViewNoReboundPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewNoDataPage") {
      FlowViewNoDataPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewMaxSpringPage") {
      FlowViewMaxSpringPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewLoadMorePage") {
      FlowViewLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewLazyRefreshAndLoadMorePage") {
      FlowViewLazyRefreshAndLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewLazyPage") {
      FlowViewLazyPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewHeaderPage") {
      FlowViewHeaderPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewHeaderAndFooterPage") {
      FlowViewHeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewFooterPage") {
      FlowViewFooterPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewFixedBottomPage") {
      FlowViewFixedBottomPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewEnableSpringPage") {
      FlowViewEnableSpringPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewAutoRefreshPage") {
      FlowViewAutoRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewAutoLoadMorePage") {
      FlowViewAutoLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewArbitrarilyStickyTopPage") {
      FlowViewArbitrarilyStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewAdaptiveTopPage") {
      FlowViewAdaptiveTopPage()
    } else 
    if (routerGetBuilderType() == "example_FlowViewAdaptiveBottomPage") {
      FlowViewAdaptiveBottomPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutTopActionBarPage") {
      FlowLayoutTopActionBarPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutStickyTopPage") {
      FlowLayoutStickyTopPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutStickyRLTopPage") {
      FlowLayoutStickyRLTopPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutSpringRatioPage") {
      FlowLayoutSpringRatioPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutRefreshPage") {
      FlowLayoutRefreshPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutRefreshHeaderAndFooterPage") {
      FlowLayoutRefreshHeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutRefreshAndLoadMorePage") {
      FlowLayoutRefreshAndLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutPositioningPage") {
      FlowLayoutPositioningPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutPage") {
      FlowLayoutPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutNoSpringPage") {
      FlowLayoutNoSpringPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutNoReboundPage") {
      FlowLayoutNoReboundPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutNoDataPage") {
      FlowLayoutNoDataPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutMaxSpringPage") {
      FlowLayoutMaxSpringPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutLoadMorePage") {
      FlowLayoutLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutLazyRefreshAndLoadMorePage") {
      FlowLayoutLazyRefreshAndLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutLazyPage") {
      FlowLayoutLazyPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutHeaderPage") {
      FlowLayoutHeaderPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutHeaderAndFooterPage") {
      FlowLayoutHeaderAndFooterPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutFooterPage") {
      FlowLayoutFooterPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutFixedBottomPage") {
      FlowLayoutFixedBottomPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutEnableSpringPage") {
      FlowLayoutEnableSpringPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutAutoLoadMorePage") {
      FlowLayoutAutoLoadMorePage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutAdaptiveTopPage") {
      FlowLayoutAdaptiveTopPage()
    } else 
    if (routerGetBuilderType() == "example_FlowLayoutAdaptiveBottomPage") {
      FlowLayoutAdaptiveBottomPage()
    } else 
    if (routerGetBuilderType() == "example_SecondFloorExample2") {
      SecondFloorExample2()
    } else 
    if (routerGetBuilderType() == "example_SecondFloorExample") {
      SecondFloorExample()
    } else 
    if (routerGetBuilderType() == "example_SecondFloorPage") {
      SecondFloorPage()
    } 

  }

}


/**
 * AUTHOR:AbnerMing
 * DATE:2026年5月21日 13时43分51秒
 * INTRODUCE:路由配置,此路由配置文件为自动生成，无特殊情况下请无须改动
 * */
export class ExampleRouterConfig implements RouterConfig {
  getModuleName(): string {
    return "example"
  }

  async initRouter(builderName: string): Promise<void> {
    return await new Promise((resolve: Function) => {
      importPath(builderName)
      routerInitBuilder(builderName, wrapBuilder(viewBuilder))
      resolve()
    })
  }
}